# Generated by Django 5.1.1 on 2024-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='gifs/')),
                ('name', models.CharField(default='name', max_length=20)),
                ('price', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
