# Generated by Django 5.1.1 on 2024-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('raiting', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Raiting',
                'verbose_name_plural': 'Raitings',
            },
        ),
    ]
