# Generated by Django 5.1.1 on 2024-10-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsnail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='picture',
            field=models.ImageField(upload_to='shopThings/gifs/'),
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('things_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsnail.shop')),
            ],
            options={
                'verbose_name': 'Purchased',
                'verbose_name_plural': 'Purchaseds',
            },
        ),
    ]
