# Generated by Django 5.1.1 on 2024-10-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsnail', '0002_alter_shop_picture_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('currentskin', models.ImageField(default='shopThings/gifs/6152297562.jpg', upload_to='shopThings/gifs/')),
                ('money', models.IntegerField(default=2100)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='purchased',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsnail.users'),
        ),
    ]
